-- OBSOLETE: therapeutic_notes was never created in D1.
-- All therapeutic data lives in the memories table under
-- categories: pattern, trigger, avoidance, schema, growth, coping, insight, homework.
-- This file is kept for historical reference only.
