-- OBSOLETE: mood_journal has been migrated to the Eukara schema.
-- PK is now user_id (not chat_id). Columns mood_label and context_summary removed.
-- Column clinical_tags added. See schema.sql for the canonical definition.
-- This file is kept for historical reference only.
